// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:713313600162:web:a0e7f64b641839e8068dfb',
    messagingSenderId: '713313600162',
    projectId: 'newsapp-4afe0',
    authDomain: 'newsapp-4afe0.firebaseapp.com',
    storageBucket: 'newsapp-4afe0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:713313600162:android:7b4af6addbf864c9068dfb',
    messagingSenderId: '713313600162',
    projectId: 'newsapp-4afe0',
    storageBucket: 'newsapp-4afe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:713313600162:ios:3feda57a6bd94565068dfb',
    messagingSenderId: '713313600162',
    projectId: 'newsapp-4afe0',
    storageBucket: 'newsapp-4afe0.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:713313600162:ios:3feda57a6bd94565068dfb',
    messagingSenderId: '713313600162',
    projectId: 'newsapp-4afe0',
    storageBucket: 'newsapp-4afe0.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:713313600162:web:b08ddb99e3801b3b068dfb',
    messagingSenderId: '713313600162',
    projectId: 'newsapp-4afe0',
    authDomain: 'newsapp-4afe0.firebaseapp.com',
    storageBucket: 'newsapp-4afe0.firebasestorage.app',
  );
}
